name: ESLint and Prettier

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.x'

      - name: Install dependencies
        run: yarn

      - name: Lint and format
        run: |
          yarn eslint .
          yarn prettier --write './**/*.{js,jsx,ts,tsx,css,md,json}' --config ./.prettierrc
